---
- name: Clone route-53-dyndns
  git: "repo={{ route53_dyndns_git_url}} dest={{ route53_dyndns_destination_path }}"

- name: write the cron file
  template: src=route53-dyndns.j2 dest=/etc/cron.hourly/route53-dyndns mode=755 owner=root
  notify:
    - restart cron
